eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka  
  instance:
    hostname: localhost  
    
microservice:
  employee-microservice:
      endpoints:
         endpoint:
             uri:http://EMPLOYEE-MICROSERVICE/employees/**
   
  employeedepartment-microservice:
      endpoints:
         endpoint:
             uri:http://EMPLOYEEDEPARTMENT-MICROSERVICE/departments/**  
